In [3]:
import pandas as pd 
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [5]:
ca=pd.read_csv('car.csv')

In [6]:
ca.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [7]:
ca.dtypes

buying      object
maint       object
doors       object
persons     object
lug_boot    object
safety      object
class       object
dtype: object

In [8]:
###Checking for NAs####

In [9]:
ca.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

In [10]:
########## converting to categorical to numerical##########

In [12]:

import category_encoders as ce

In [13]:
encoder = ce.OrdinalEncoder(cols=['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety','class'])


ca= encoder.fit_transform(ca)

In [14]:
ca.head()

buying  maint  doors  persons  lug_boot  safety  class
0       1      1      1        1         1       1      1
1       1      1      1        1         1       2      1
2       1      1      1        1         1       3      1
3       1      1      1        1         2       1      1
4       1      1      1        1         2       2      1

In [15]:
###Spliting Train data into Train and Test data sets,
###train data is for model bulding,
###test data is for checking model performance.

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
ca_train,ca_test = train_test_split(ca, test_size = 0.2,random_state=2)

In [18]:
####Rearranging index after random selection from train data set###

In [19]:
ca_train.reset_index(drop=True,inplace=True)
ca_test.reset_index(drop=True,inplace=True)

In [20]:
###Splitting data to dependent variables data set and target variable data set####

In [21]:
x_train=ca_train.drop(["safety"],1)
y_train=ca_train["safety"]
x_test=ca_test.drop(["safety"],1)
y_test=ca_test["safety"]

In [22]:
from sklearn.tree import DecisionTreeClassifier

In [23]:

clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=0)
# fit the model
clf_gini.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=0)

In [24]:
y_pred_gini = clf_gini.predict(x_test)

In [25]:
from sklearn.metrics import accuracy_score

print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, y_pred_gini)))

Model accuracy score with criterion gini index: 0.4740


In [26]:
print('Training set score: {:.4f}'.format(clf_gini.score(x_train, y_train)))

print('Test set score: {:.4f}'.format(clf_gini.score(x_test, y_test)))

Training set score: 0.5398
Test set score: 0.4740


In [27]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_gini)

print('Confusion matrix\n\n', cm)

Confusion matrix

 [[77 38  0]
 [48 65 14]
 [30 52 22]]


In [28]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_gini))

              precision    recall  f1-score   support

           1       0.50      0.67      0.57       115
           2       0.42      0.51      0.46       127
           3       0.61      0.21      0.31       104

    accuracy                           0.47       346
   macro avg       0.51      0.46      0.45       346
weighted avg       0.50      0.47      0.45       346



In [29]:
################program ends#####################

In [30]:
submission=pd.DataFrame((list(y_pred_gini)),
                       columns=['safety'])

In [32]:
submission.to_csv('sample_car1.csv', index=False)